### PR TITLE
Migrate to gomarkdown

### PR DESCRIPTION
**Pull request by jessp01**
As the BlackFriday project is no longer active, this pull migrates us to [gomarkdown](https://github.com/gomarkdown/markdown)

### CODE REVIEW

**Review by mandolyte — APPROVED** [review]
Thanks @jessp01

**Comment by jessp01** [comment]
Hi @mandolyte ,

Yes, that's a relic from when we moved mdtopdf.go into `cmd/md2pdf`, it's not related to the migration to `gomarkdown` of course but I fixed it just now.

On a more general level, do you reckon perhaps we should move these resource files (russian.md, test.md, helvetica_1251.json, etc) into a separate directory?

Cheers,

**Comment by jessp01** [comment]
@mandolyte , obviously, it's your call:) But I agree it's significant, even if I've gone to some lengths to make sure it's not something end users will notice (to wit: to ensure I haven't broken anything). I don't think going with v2.0.0 is unreasonable.

**Comment by mandolyte** [comment]
Sounds good... will wait until tomorrow... won't have time to release today. Thanks for all the work you have invested!!

**Pull request merged**
